name: vuln workflow_run

on:
    pull_request:

jobs:
    firstjob:
        runs-on: ubuntu-24.04
        steps:
            - name: firststep
              run: |
               echo "sha: ${{github.event.pull_request.head.sha}}"
               echo "github sha ${{github.sha}}"